Dev dump
CDCgov/dibbs-query-connector pull request #158
Opened 2024-11-13 21:56 UTC by bamader

# Mount a pg_dump extract to docker dev

## Summary

This PR creates a `.sql` dump of the PG database just after the eRSD has successfully been loaded via a local `docker compose` run. It has been mounted into the docker dev volume to automatically run as an entrypoint script when running in dev mode.

## Related Issue

Fixes #122 

## Additional Information

Added a readme with the command needed to create the dump file in case we ever want to update the dev dump.

2024-11-13 22:22 UTC, m-goggins requested changes
Looks good! I believe we need to mount the same volume to the db docker-compose-e2e so that the data is available for end to end tests.

2024-11-14 13:39 UTC, bamader commented
Actually that reminds me that we need to also call the valueset insertion functions for the DIBBs hardcoded values / JSON dump file that you wrote at `/src/app/assets/DIBBS_Custom_ValueSets.json` in the create DB functions overall. This dump doesn't include those so our e2e's will totally fail. I'll update the code and the dump mount.

2024-11-14 13:50 UTC, robertandremitchell reviewed
makes sense to me. I wonder if we actually want to commit the `vs_dump.sql` to github or just have it locally? or do we need to upload it for tests to pass successfully?

2024-11-14 14:17 UTC, bamader commented
@robertandremitchell I believe we'll need to upload it for tests to pass once we take the migrations out. I'll have to modify the github workflow to take advantage of it. I think it's also probably good to commit it in case anyone else needs to pull things down and be able to iterate quickly, e.g. a designer who wants to test out a new feature's appearance.

2024-11-22 15:07 UTC, robertandremitchell reviewed
running into some issues getting this to run either in dev mode or docker. I ran into some of these docker issues on Marcelle's old PRs, so not sure how much this is new, but attached is what I am currently running into. It is working to...some degree for me in dev, while it's breaking entirely in docker. below is the screenshot of what happens when I click the Create Query button.

<img width="1037" alt="Screenshot 2024-11-22 at 10 07 02 AM" src="https://github.com/user-attachments/assets/204307d8-ac9d-4abf-9018-a15b4190f4b9">

[error_message.txt](https://github.com/user-attachments/files/17872079/error_message.txt)

2024-11-22 15:07 UTC, robertandremitchell commented on query-connector/VS_DUMP_INFO.md
> +2. Load the eRSD and valuesets into the DIBBs DB by using the `Create DB` button on the `/queryBuilding` page. Optionally, use DBeaver to verify that valuesets exist in the database.
minor quibble; button is called `Create Query`

2024-11-22 18:17 UTC, bamader commented
@robertandremitchell That error log means that our default seed stuff isn't being copied over into the docker container from its base directory like the Dockerfile is supposed to instruct it. Could you run a `docker system prune` and see if it works? Just tried it again for myself, and if I `docker compose up` from nothing or `npm run dev` from nothing, both work totally fine for me :/

2024-11-22 19:33 UTC, bamader commented
@robertandremitchell Actually your error log helped me find a problem! In dev mode, we should never need to be accessing those seeding scripts because it loads everything from the DB mount--i.e. we only seed from a docker run where we're trying to do the data dump, not once we're already in dev mode. I've moved those inserts into the `if` check for whether there's already data in the DB, so see if that helps!

2024-11-22 21:18 UTC, robertandremitchell commented
> @robertandremitchell Actually your error log helped me find a problem! In dev mode, we should never need to be accessing those seeding scripts because it loads everything from the DB mount--i.e. we only seed from a docker run where we're trying to do the data dump, not once we're already in dev mode. I've moved those inserts into the `if` check for whether there's already data in the DB, so see if that helps!

thanks! that seems to have fixed dev mode for me. still trying to figure out what is happening with my docker error when I click the button. This is the same as I was getting on Marcelle's prior PR so idk if it's something specific to my docker. I'll try updating, pruning, then building fresh 🤞🏽 

```
query-connector-1  | TypeError: Cannot read properties of undefined (reading '0')
query-connector-1  |     at /app/.next/server/chunks/652.js:122:2119
query-connector-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
query-connector-1  |     at async C (/app/.next/server/chunks/652.js:122:2089)
query-connector-1  |     at async /app/.next/server/app/queryBuilding/page.js:1:5766
query-connector-1  |     at async Promise.all (index 50)
query-connector-1  |     at async c (/app/.next/server/app/queryBuilding/page.js:1:5722)
query-connector-1  |     at async d (/app/.next/server/app/queryBuilding/page.js:1:7354)
query-connector-1  |     at async /app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:418
query-connector-1  |     at async rE (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:15:7978)
query-connector-1  |     at async r7 (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:18:1144)
```

2024-11-25 14:56 UTC, robertandremitchell commented
@bamader , with some help from Marcelle and a fresh Docker install, I seem to have made some progress. Based on the log (attached), it broadly seems to have worked. I have a count of 226 conditions, 33810 conditions, and 1390 valuesets, which broadly seems right. However, category is NULL for all conditions, which is leading to a weird display:

<img width="1086" alt="Screenshot 2024-11-25 at 9 30 57 AM" src="https://github.com/user-attachments/assets/c29013a7-9026-49a3-8c41-e63d1f9a3812">


I'm not sure if this is a sequencing issue with the migrations and the creation of the eRSD data, or something else. At some point, I had gotten this to render correctly on `npm run dev`; however, now I'm getting the same issue with null category.


[log.txt](https://github.com/user-attachments/files/17904649/log.txt)

2024-11-25 16:24 UTC, bamader commented
@robertandremitchell Yeah it looks like a sequencing problem. Migration 7 is the category data which currently in main relies on a staging table that's a bit harder to use than standard pulldowns. I _think_ I should be able to just make this an additional asset during seeding though, so let me give that a try. Good find!

2024-11-25 17:22 UTC, m-goggins commented
I ran into no errors and things started up super quickly when I ran `npm run dev-win` but I've got slightly different numbers from Rob in the DB 😬 228 conditions, 1406 valuesets, and 34,034 concepts

2024-11-25 19:07 UTC, m-goggins approved these changes

2024-11-25 19:14 UTC, bamader commented
@robertandremitchell Okay category data should be tracked now (and as an added plus, we get to delete off the last non-setup migration!). Also, from a fully fresh load on both docker compose and `npm run dev`, I see the exact counts of valuesets, concepts, and conditions that Marcelle does (which I also know from hand counting, at least on the condition side, is actually correct 😅 ... yes I had to do that at one point...)

2024-11-25 20:02 UTC, robertandremitchell reviewed
Looks great! worked for me, accept these two conditions had no categories, for me:


```
Invasive Group B beta-hemolytic streptococcal disease

Invasive Group A beta-hemolytic streptococcal disease
```

2024-11-25 20:31 UTC, bamader commented
@robertandremitchell Ah good find, the parsing script I used must've clipped a code or something. I'll add that back in!

2024-11-25 21:06 UTC, bamader commented
Okay missing condition categories should now be fixed. @robertandremitchell Want to give you a final checking chance before I merge anything so let me know when you're satisfied!

2024-11-25 21:43 UTC, robertandremitchell approved these changes
looks good! thanks to you both @m-goggins and @bamader for helping me debug!

2024-11-26 13:36 UTC, merged