Shanice/transition ecs infra
CDCgov/dibbs-query-connector pull request #222
Opened 2024-12-17 03:58 UTC by shanice-skylight

# PULL REQUEST

## Summary

What changes are being proposed? For PRs that include UX/UI changes please make sure to describe their scope and highlight any specific areas that design reviews should focus.

## Related Issue

Fixes #

## Additional Information

Anything else the review team should know?

## Checklist

- [ ] Descriptive Pull Request title
- [ ] Link to relevant issues
- [ ] Provide necessary context for design reviewers
- [ ] Update documentation

2025-01-06 16:37 UTC, alismx commented on .github/workflows/ecs_terraform.yaml
> +          ls -al
This could be removed.

Another note: do you have a job that will only plan? That is useful when debugging or planning upgrades. It's nice to see changes beforehand.

2025-01-06 16:40 UTC, alismx commented on .gitignore
> +.terraform/modules/ecs
Seems like you may also want to delete and ignore `terraform/implementation/ecs/.terraform/*`

2025-01-06 18:02 UTC, shanice-dp commented on .gitignore
> +.terraform/modules/ecs
Done

2025-01-06 18:10 UTC, shanice-skylight commented on .gitignore
> +.terraform/modules/ecs
Done

2025-01-06 18:11 UTC, shanice-skylight commented on .github/workflows/ecs_terraform.yaml
> +          ls -al
Removed debugging code. You make a good point, I added a separate terraform plan workflow

2025-01-06 19:13 UTC, nickclyde requested changes
Looking great, just a few comments:

2025-01-06 19:13 UTC, nickclyde commented on .github/workflows/ecs_terraform.yaml
> +      - "**"
I think we should remove the pull request trigger - we only want manual runs and runs on merge to main, right?

2025-01-06 19:13 UTC, nickclyde commented on .github/workflows/ecs_terraform.yaml
> +          PROJECT: ${{ vars.PROJECT }}
I think the OWNER and PROJECT variables are unused, can we remove them?

2025-01-06 19:13 UTC, nickclyde commented on terraform/.terraform/environment
> +dev
Should `.terraform` be gitignored? same for all of the files under `.terraform`

2025-01-06 19:55 UTC, alismx commented on terraform/implementation/ecs/.terraform/modules/modules.json
> +{"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"ecs","Source":"registry.terraform.io/CDCgov/dibbs-ecr-viewer/aws","Version":"0.3.0","Dir":".terraform/modules/ecs"},{"Key":"rds","Source":"registr
Is there a need for this?  I've not seen a need for in a repo before. AFAIK, This directory and everything under this directory should be deleted.

2025-01-06 23:06 UTC, shanice-skylight commented on terraform/.terraform/environment
> +dev
Yes so that github will not use any local plugins or module changes I've made. It'll be forced to grab the modules for itself each time.

2025-01-06 23:10 UTC, shanice-skylight commented on terraform/implementation/ecs/.terraform/modules/modules.json
> +{"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"ecs","Source":"registry.terraform.io/CDCgov/dibbs-ecr-viewer/aws","Version":"0.3.0","Dir":".terraform/modules/ecs"},{"Key":"rds","Source":"registr
No, I did not create it. Must have been automatically added. I added this line to the gitignore: `terraform/implementation/ecs/.terraform/*`

2025-01-06 23:18 UTC, shanice-skylight commented on .github/workflows/ecs_terraform.yaml
> +      - "**"
Done

2025-01-06 23:19 UTC, shanice-skylight commented on terraform/implementation/ecs/.terraform/modules/modules.json
> +{"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"ecs","Source":"registry.terraform.io/CDCgov/dibbs-ecr-viewer/aws","Version":"0.3.0","Dir":".terraform/modules/ecs"},{"Key":"rds","Source":"registr
Removed all .terraform directories.

2025-01-06 23:44 UTC, shanice-skylight commented on .github/workflows/ecs_terraform.yaml
> +          PROJECT: ${{ vars.PROJECT }}
Done

2025-01-06 23:47 UTC, shanice-skylight commented
All comments addressed and review changes made, ready for last review.

2025-01-07 00:04 UTC, nickclyde approved these changes
Fantastic work! 🚀

2025-01-07 00:32 UTC, merged

2025-01-07 00:33 UTC, alismx approved these changes
It looks pretty ready! My comments are just about extra comments that have been left. While I'd love to see these cleaned up, I won't block it on that. Feel free to clean them up now or do a follow-up PR if that's easier. Approved!

2025-01-07 00:33 UTC, alismx commented on terraform/implementation/ecs/_variable.tf
> +# Manually update to set the version you want to run
This comment could be removed.

2025-01-07 00:33 UTC, alismx commented on terraform/implementation/ecs/main.tf
> +  # If intent is to pull from the phdi GHCR, set disable_ecr to true (default is false)
Since this is used internally by the qc team and not a template used by others, the comments in this section could be removed.